### ISSUE TITLE
Can this tool support other graphdb support Gremlin like JanushGraph? 

### ISSUE THREAD

**Issue by mingjinc** [kensho-technologies/graphql-compiler#320]

**Comment by obi1kenobi** [comment]
Hi @mingjinc! Yes, there's nothing preventing the compiler from outputting Gremlin compatible with other databases as well. Our dev team is only familiar with OrientDB's implementation of Gremlin so that's the only integration we have working at the moment, but if you'd like to contribute, we'd be happy to point you in the right direction toward adding Gremlin support for other databases such as JanusGraph as well.
